site_name: STEM Robots
site_description: 'Resources for teaching computational thinking using low-cost robots. Content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/stem-robots'
repo_url: 'https://github.com/dmccreary/stem-robots'

nav:
  - Home: index.md
  - about.md
  - Gallery: gallery.md
  - Getting Started:
    - setup/index.md
    - setup/05-thonny-installation.md
    - setup/10-base-kit-assembly.md
    - setup/20-parts-list.md
  - Lessons:
    - lessons/index.md
    - lessons/03-robot-parts.md
    - lessons/05-batteries.md
    - lessons/10-dc-motors.md
    - lessons/15-motor-direction.md
    - lessons/20-motor-speed.md
    - lessons/25-pwm.md
    - lessons/30-testing-motor-connections.md
    - lessons/35-dance.md
    - lessons/40-i2c-bus.md
    - lessons/45-sensors.md
    - lessons/50-tof-sensors.md
    - lessons/55-ultrasonic-sensors.md
  - Kits:
    - kits/adjust/index.md
    - kits/base/index.md
    - kits/bump-switch/index.md
    - kits/display/index.md
    - kits/line-follower/index.md
    - kits/ultrasonic/index.md
  - FAQ: faq.md
  - Glossary: glossary.md
  - References: references.md
  - License: license.md
  - Contact: contact.md

 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX